pool:
  vmImage: 'VS2017-Win2016'

steps:
- script: powershell Write-Host $PSVersionTable.PSVersion
  displayName: 'PS Version check'

- script: powershell .\scripts\build.ps1
  displayName: 'Build'

- script: powershell .\scripts\test.ps1
  displayName: 'Test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    failOnStandardError: 'true'

- powershell: |
    $resultTrx = "src/Belial.Tests/TestResults/testresults.trx"
    if($(Get-Content $resultTrx | Out-String) -match 'outcome="Failed"')
    {
        #  will produce $LASTEXITCODE=1
        Write-Error "tests failed"
    }
    else
    {
        Write-Host "No test failures"
    }
  displayName: Check for test failures

- powershell: az storage blob download-batch -d "src/Belial/bin/Debug/netcoreapp2.1" -s $(apicredscontainer) --account-name $(websitestoragename) --account-key "$(websitestoragekey)" --verbose
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Prepare Sheet Credentials'

- script: powershell .\scripts\package.ps1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Package'

- script: powershell .\scripts\deploy.ps1 -appServiceName "$(appservicename)" -Username "$(appserviceusername)" -Password "$(appservicepassword)"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Deploy Backend'

- powershell: az storage blob upload-batch -d `$web -s "$(Build.Repository.LocalPath)\src\Belial.Blazor\bin\Release\netstandard2.0\publish\Belial.Blazor\dist" --account-name $(websitestoragename) --account-key "$(websitestoragekey)" --verbose
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Deploy Website'

- powershell: az storage blob upload -c `$web -n "_framework\wasm\mono.wasm" -f "$(Build.Repository.LocalPath)\src\Belial.Blazor\bin\Release\netstandard2.0\publish\Belial.Blazor\dist\_framework\wasm\mono.wasm" --account-name $(websitestoragename) --account-key "$(websitestoragekey)" --content-type "application/wasm" --verbose
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Deploy Website - Wasm'