pool:
  vmImage: 'VS2017-Win2016'

steps:
- script: powershell .\scripts\build.ps1
  displayName: 'Build'

- script: powershell .\scripts\test.ps1
  displayName: 'Test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'