pool:
  vmImage: 'VS2017-Win2016'

steps:
- script: powershell Write-Host $PSVersionTable.PSVersion
  displayName: 'PS Version check'

- script: powershell .\scripts\build.ps1
  displayName: 'Build'

- script: powershell .\scripts\test.ps1
  displayName: 'Test'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    failOnStandardError: 'true'

- powershell: |
    $resultTrx = "src/Belial.Tests/TestResults/testresults.trx"
    if($(Get-Content $resultTrx | Out-String) -match 'outcome="Failed"')
    {
        #  will produce $LASTEXITCODE=1
        Write-Error "tests failed"
    }
    else
    {
        Write-Host "No test failures"
    }
  displayName: Check for test failures

- script: powershell .\scripts\package.ps1
  displayName: 'Package'

- script: powershell .\scripts\deploy.ps1 -appServiceName "$(appservicename)" -Username "$(appserviceusername)" -Password "$(appservicepassword)"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Deploy Backend'

# - script: powershell .\scripts\deploy-website.ps1 -storageUrl ""$(websitestorageurl)"" -sasToken ""$(websitesastoken)""
#   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
#   displayName: 'Deploy Website'